name: 'Example action'
description: ''
author: Miguel Savignano
inputs:
  github_token:
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-merge'
  color: 'purple'
