name: Check coverage
on:
  push:
    branches:
      - 'master'

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: devmasx/coverage-check-action@v1.1.0
        with:
          type: lcov
          result_path: coverage/example.lcov
          min_coverage: 90
          token: ${{secrets.GITHUB_TOKEN}}
