name: Merge branch now
on:
  push:
    branches:
      - 'release/*'

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge to master
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: release/v4
          target_branch: master
          github_token: ${{ github.token }}
