name: Merge branch labeled
on:
  pull_request:
    types: [labeled]

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge to develop
        uses: devmasx/merge-branch@develop
        with:
          label_name: 'merged in develop'
          target_branch: develop
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
