name: check mege branch
on:
  push:
    branches:
      - '*'
jobs:
 set-merged-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@action-logs
      - run: echo "Hello world"
      - name: Merge staging -> uat
        uses: devmasx/merge-branch@action-logs
        with:
          type: not_found
          from_branch: master
          target_branch: staging
          github_token: ${{ github.token }}
