name: Merge branch now
on:
  push:
    branches:
      - 'release/*'

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge to master
        uses: devmasx/merge-branch@v1.3.1
        with:
          label_name: ready to launch
          target_branch: master
          github_token: ${{ github.token }}
