name: check mege branch
on:
  push:
    branches:
      - 'staging'
jobs:
 set-merged-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: echo "Hello world"
      - name: check merge in staging
        uses: devmasx/merge-branch@develop
        with:
          type: 'merged-label'
          label_name: merged-in-staging
          github_token: ${{ github.token }}
