name: Merge branch labeled
on:
  pull_request:
    types: [labeled]
    # branches:
    #   - release/*
    #   - hotfix/*
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: echo ${{ github.ref }}
      - run: echo ${{ github.event.action }}
      - run: echo ${{ github.event.label.name }}
      - run: echo ${{ github.event.pull_request.head.ref }}
      - run: cat $GITHUB_EVENT_PATH
      - name: Merge to staging
        if: contains(github.event.pull_request.head.ref, 'release/') || contains(github.event.pull_request.head.ref, 'hotfix/')
        uses: devmasx/merge-branch@v1.3.1
        with:
          label_name: ready to launch
          target_branch: staging
          github_token: ${{ github.token }}
