name: Merge branch now
on:
  push:
    branches:
      - "*"
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: staging -> master
        uses: devmasx/merge-branch@fix-env-empty
        with:
          type: now
          target_branch: master
          from_branch: staging
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: master -> develop
        uses: devmasx/merge-branch@fix-env-empty
        with:
          type: now
          target_branch: develop
          from_branch: master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: develop -> staging
        uses: devmasx/merge-branch@fix-env-empty
        with:
          type: now
          target_branch: staging
          from_branch: develop
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
