name: Merge branch labeled
on:
  pull_request:
    types: [labeled]
    # branches:
    #   - release/*
    #   - hotfix/*
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: echo ${{ github.ref }}
      - name: Merge to master
        if: contains(github.ref, 'refs/release/')
        uses: devmasx/merge-branch@v1.3.1
        with:
          label_name: ready to launch
          target_branch: staging
          github_token: ${{ github.token }}
