name: Set merged label on staging
on:
  push:
    branches:
      - 'staging'
jobs:
 set-merged-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set merged label on staging
        uses: devmasx/merge-branch@develop
        with:
          type: 'merged-label'
          github_token: ${{ github.token }}
