name: Merge branch now
on:
  push:
    branches:
      - 'release/*'

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge to master
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          base_branch: master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
