name: Example
on:
  push:
    branches:
      - 'local-action'

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use local example-action
        uses: ./.github/actions/example-action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
